name: CI

on:
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  azure-devops-ci:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/icarostuart/HateoasNet'
        azure-pipeline-name: 'HateoasNet SonarCloud'
        azure-devops-token: '${{ secrets.HATEOASNET_CI_AZURE_DEVOPS_TOKEN }}'
